harness:
  sentry: false
  dependencies:
    soft:
      - accounts
      - accounts-api
      - common
      - volumemanager
      - workspaces
      - workflows
      - jupyterhub
      - jupyterlab
